import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser, hasRole } from "@/lib/auth";
import { query } from "@/lib/db";

function escapeCsv(value: unknown): string {
  if (value === null || value === undefined) return '""';
  const str = String(value);
  return `"${str.replace(/"/g, '""')}"`;
}

export async function GET(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!hasRole(user, ["admin"])) {
    return NextResponse.json(
      { error: "Forbidden: Admin access required to generate reports." },
      { status: 403 }
    );
  }

  const { searchParams } = new URL(req.url);
  let month = searchParams.get("month")?.trim() || "";
  const format = searchParams.get("format") || "csv";

  // Validate or default month (YYYY-MM)
  if (!/^\d{4}-(?:0[1-9]|1[0-2])$/.test(month)) {
    const now = new Date();
    const yyyy = now.getFullYear();
    const mm = String(now.getMonth() + 1).padStart(2, "0");
    month = `${yyyy}-${mm}`;
  }

  const [yearStr, monthStr] = month.split("-");
  const year = Number(yearStr);
  const monthNum = Number(monthStr);
  const lastDay = new Date(year, monthNum, 0).getDate();

  const startDate = `${month}-01 00:00:00`;
  const endDate = `${month}-${String(lastDay).padStart(2, "0")} 23:59:59`;

  const tickets = await query<{
    id: string;
    title: string;
    description: string;
    status: string;
    priority: string;
    category_id: number | null;
    category_name: string | null;
    created_by: number;
    created_by_name: string;
    created_by_email?: string;
    assigned_to: number | null;
    assigned_to_name: string | null;
    created_at: string;
    updated_at: string;
    resolved_at: string | null;
  }>(
    `SELECT t.id, t.title, t.description, t.status, t.priority, t.category_id,
            t.created_by, t.assigned_to, t.created_at, t.updated_at, t.resolved_at,
            c.name AS category_name,
            cu.name AS created_by_name, cu.email AS created_by_email,
            au.name AS assigned_to_name
     FROM tickets t
     LEFT JOIN categories c ON t.category_id = c.id
     LEFT JOIN users cu ON t.created_by = cu.id
     LEFT JOIN users au ON t.assigned_to = au.id
     WHERE t.created_at >= ? AND t.created_at <= ?
     ORDER BY t.created_at DESC`,
    [startDate, endDate]
  );

  const total = tickets.length;
  const openCount = tickets.filter((t) => t.status === "open").length;
  const inProgressCount = tickets.filter((t) => t.status === "in_progress").length;
  const resolvedCount = tickets.filter((t) => t.status === "resolved").length;
  const closedCount = tickets.filter((t) => t.status === "closed").length;
  const resolutionRate =
    total > 0 ? Math.round(((resolvedCount + closedCount) / total) * 100) : 0;

  if (format === "json") {
    return NextResponse.json({
      month,
      startDate,
      endDate,
      summary: {
        total,
        open: openCount,
        inProgress: inProgressCount,
        resolved: resolvedCount,
        closed: closedCount,
        resolutionRate,
      },
      tickets,
    });
  }

  // Format as CSV
  const lines: string[] = [];
  lines.push("IT HELPDESK MONTHLY REPORT");
  lines.push(`Report Month,${escapeCsv(month)}`);
  lines.push(`Period Start,${escapeCsv(startDate)}`);
  lines.push(`Period End,${escapeCsv(endDate)}`);
  lines.push(`Generated On,${escapeCsv(new Date().toISOString())}`);
  lines.push(`Generated By,${escapeCsv(`${user.name} (${user.email})`)}`);
  lines.push("");
  lines.push("SUMMARY METRICS");
  lines.push(`Total Tickets Created,${total}`);
  lines.push(`Open Tickets,${openCount}`);
  lines.push(`In Progress Tickets,${inProgressCount}`);
  lines.push(`Resolved Tickets,${resolvedCount}`);
  lines.push(`Closed Tickets,${closedCount}`);
  lines.push(`Resolution Rate,${resolutionRate}%`);
  lines.push("");
  lines.push("TICKET RECORDS");
  lines.push(
    [
      "Ticket ID",
      "Title",
      "Status",
      "Priority",
      "Category",
      "Reported By",
      "Reporter Email",
      "Assigned To",
      "Created At",
      "Resolved At",
      "Description",
    ]
      .map(escapeCsv)
      .join(",")
  );

  for (const t of tickets) {
    lines.push(
      [
        t.id,
        t.title,
        t.status,
        t.priority,
        t.category_name ?? "—",
        t.created_by_name ?? "Unknown",
        t.created_by_email ?? "",
        t.assigned_to_name ?? "Unassigned",
        t.created_at,
        t.resolved_at ?? "—",
        t.description ?? "",
      ]
        .map(escapeCsv)
        .join(",")
    );
  }

  const csv = lines.join("\r\n");

  return new NextResponse(csv, {
    status: 200,
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="IT-HelpDesk-Monthly-Report-${month}.csv"`,
      "Cache-Control": "no-store",
    },
  });
}
